[window]
option_as_alt = "OnlyLeft"
opacity = 0.9
dynamic_padding = false

[window.padding]
x = 25
y = 20

[env]
SHELL = "fish"
EDITOR = "nvim"
PAGER = "less"
VISUAL = "nvim"

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[bell]
duration = 5

